 export const Types = {
    FETCH_TRACKS_START: 'FETCH_TRACKS_START',
    FETCH_TRACKS_SUCCESS: 'FETCH_TRACKS_SUCCESS',
    FETCH_TRACKS_ERROR: 'FETCH_TRACKS_ERROR',

    FETCH_ARTIST_START: 'FETCH_ARTIST_START',
    FETCH_ARTIST_SUCCESS: 'FETCH_ARTIST_SUCCESS',
    FETCH_ARTIST_ERROR: 'FETCH_ARTIST_ERROR',

    FETCH_SEARCH_START: 'FETCH_SEARCH_START',
    FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
    FETCH_SEARCH_ERROR: 'FETCH_SEARCH_ERROR',
}
