 export const Types = {
    FETCH_TRACKS_START: 'FETCH_TRACKS_START',
    FETCH_TRACKS_SUCCESS: 'FETCH_TRACKS_SUCCESS',
    FETCH_TRACKS_ERROR: 'FETCH_TRACKS_ERROR',

    FETCH_ARTIST_START: 'FETCH_ARTIST_START',
    FETCH_ARTIST_SUCCESS: 'FETCH_ARTIST_SUCCESS',
    FETCHARTISTS_ERROR: 'FETCH_ARTIST_ERROR',
}
